# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'abi-beer-app' do
  # Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

  # Pods for abi-beer-app
pod 'SDWebImage', '~>5.0'

end
